import { INPUT_TYPES } from './input-types';

export const INPUT_OBJECTS = [
  {
    controlName: '',
    formControlName: '',
    type: INPUT_TYPES.INPUT,
    placeholder: 'Enter Text Input',
    label: 'Text Input',
    hint: 'Hint for text',
    showClear: false,
    validation: {
      minLength: 'Min Length error',
      maxLength: 'Max length error',
      required: 'Required',
      pattern: 'Pattern not matching',
      min: 'Min number',
      max: 'Max number',
    },
    options: [],
    defaultValue: null,
    required: true,
    validationsAvailable: [
      { name: 'minLength', value: null, addValidation: false },
      { name: 'maxLength', value: null, addValidation: false },
      { name: 'required', value: null, addValidation: true },
      { name: 'pattern', value: null, addValidation: false },
      { name: 'min', value: null, addValidation: false },
      { name: 'max', value: null, addValidation: false },
    ],
  },
  {
    controlName: '',
    formControlName: '',
    type: INPUT_TYPES.DROPDOWN,
    placeholder: 'Select Dropdown Item',
    label: 'Choose here',
    hint: '',
    showClear: false,
    validation: [],
    options: [
      { label: 'Label 1', value: 1 },
      { label: 'Label 2', value: 2 },
    ],
    required: true,
    defaultValue: null,
    validationsAvailable: [],
  },
  {
    controlName: '',
    formControlName: '',
    type: 'radio',
    placeholder: 'Select Radio item',
    label: 'Select Item from radio',
    hint: 'radio selection',
    showClear: false,
    validation: [],
    options: [
      { label: 'Label 1', value: 1 },
      { label: 'Label 2', value: 2 },
    ],
    required: true,
    defaultValue: null,
    validationsAvailable: [],
  },
  {
    controlName: '',
    formControlName: '',
    type: 'checkbox',
    placeholder: 'Checkbox Selection',
    label: 'Label',
    hint: '',
    showClear: false,
    validation: [],
    options: [],
    required: true,
    defaultValue: true,
    validationsAvailable: [],
  },
  {
    controlName: '',
    formControlName: '',
    type: 'datepicker',
    placeholder: 'Choose Valid Date',
    label: 'Select Date',
    hint: 'MM/DD/YYYY',
    showClear: false,
    validation: [],
    options: [],
    checkboxValue: null,
    validationsAvailable: [],
    required: true,
    defaultValue: new Date(),
  },
];
